name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: static check with findbugs
      run: ./gradlew findbugs
    - name: static check with lint
      run: ./gradlew lint 
    - uses: yutailang0119/action-android-lint@v1.0.2
      with:
        xml_path: ${{ github.workspace }}/app/build/reports/lint-results.xml
    - uses: actions/upload-artifact@v2      
      with:
        name: apk_artifact
        path: app/build/outputs/apk/**/*.apk
