/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mine_dearbear_utils_JniUtilTest */

#ifndef _Included_com_mine_dearbear_utils_JniUtilTest
#define _Included_com_mine_dearbear_utils_JniUtilTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mine_dearbear_utils_JniUtilTest
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mine_dearbear_utils_JniUtilTest_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
